# Generated by Django 2.1.1 on 2019-02-21 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=100)),
                ('album_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albumns.Album')),
            ],
        ),
    ]
