# Generated by Django 2.1.1 on 2019-02-23 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albumns', '0002_auto_20190223_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('album_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='albumns.Album')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albumns.Image')),
            ],
        ),
    ]
